### ISSUE TITLE
【docker-compose】command : yarn

### ISSUE THREAD

**Issue by urashin** [dx-junkyard/sports-barrier-free-liff-2#2]
docker-compose.ymlの設定
```
version: '3'

services:
  sports-barrier-free-liff:
    build: .
    image: sports-barrier-free-liff
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3001:3001"
    command: yarn dev:proxy
```
